from pydantic import BaseModel, ConfigDict, Field
from datetime import datetime
from schemas.course import CourseID
from schemas.student import StudentID
from typing import Annotated

EnrollmentID = Annotated[int, Field(
        ...,
        title='Unique primary key for each enrollment',
        description='Unique primary key for each enrollment auto-generated by database',
        gt=0,
        example=3
    )
]

class EnrollmentBase(BaseModel):
    student_id: StudentID
    course_id: CourseID

# Don't allow users to set or change date
class EnrollmentCreate(EnrollmentBase):
    pass

class EnrollmentGet(EnrollmentBase):
    date: datetime = Field(
        ...,
        title='Enrollment Date',
        description='The date when the student enroll in the course'
    )

    model_config = ConfigDict(from_attributes=True)
