from pydantic import BaseModel, ConfigDict, Field

class StudentBase(BaseModel):
    name: str = Field(
        ...,
        title='Student Name',
        pattern="^[A-Za-z '-]+$",
        min_length=5,
        max_length=50,
        example='Adam Chong Wei Jie'
    )
    age: int = Field(
        ...,
        title='Age of student',
        gt=0,
        lt=100,
        example=18
    )

class StudentCreate(StudentBase):
    password: str = Field(
        ...,
        title="Password of student's account",
        min_length=5,
        max_length=20
    )

class StudentGet(StudentBase):
    id: int = Field(
        ...,
        title='Unique primary key for each student',
        description='Unique primary key for each student auto-generated by database',
        gt=0,
        example=3
    )

    model_config = ConfigDict(from_attributes=True)

class StudentUpdate(BaseModel):
    name: str | None = Field(
        None,
        title='Student Name',
        pattern='^[A-Za-z ]+$',
        min_length=5,
        max_length=50,
        example='Adam Chong Wei Jie'
    )
    age: int | None = Field(
        None,
        title='Age of student',
        gt=0,
        lt=100,
        example=18
    )
    old_pw: str | None = Field(
        None,
        title="Old password of student's account",
        min_length=5,
        max_length=20
    )
    new_pw: str | None = Field(
        None,
        title="New password of student's account",
        min_length=5,
        max_length=20
    )
